"""Add additional fields to BloodRequest model

Revision ID: 29b25b8773de
Revises: a81d5339b186
Create Date: 2025-03-28 22:14:06.357463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b25b8773de'
down_revision = 'a81d5339b186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_type', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('units_needed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('urgency_level', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('urgency_level')
        batch_op.drop_column('units_needed')
        batch_op.drop_column('blood_type')

    # ### end Alembic commands ###
