"""added field available

Revision ID: 996407ab3a65
Revises: 29b25b8773de
Create Date: 2025-03-29 13:56:24.129809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996407ab3a65'
down_revision = '29b25b8773de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_donation_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_column('last_donation_date')

    # ### end Alembic commands ###
